export const  SELECTED_OPTIONS ='SELECTED_OPTIONS'
export const  CURRENT_WEIGHT ='CURRENT_WEIGHT'
export const  CURRENT_WEIGHT_UNIT ='CURRENT_WEIGHT_UNIT'
export const  SET_USER_DETAIL ='SET_USER_DETAIL'
export const  GOAL_WEIGHT_UNIT ='GOAL_WEIGHT_UNIT'
export const  GOAL_WEIGHT ='GOAL_WEIGHT'
export const  GOAL_TYPE ='GOAL_TYPE'
export const  SET_INTENSITY ='SET_INTENSITY'
export const  SET_REMEMBER ='SET_REMEMBER'





